Vagrant.configure("2") do |config|
  config.vm.box = "hfm4/centos7"
  config.vm.hostname = "epbygomw0024t1"
  config.vm.network "private_network", ip: "192.168.56.2"

  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "epbygomw0024t1"

    vb.customize ["modifyvm", :id, "--memory", "16384"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
end
