sample:
  lexicon:
    export-url: http://{instance-id}/mobile/rest/fxresources/lexicons/nlpsvc/export/{account-id}/{lexicon-type}
    # export-url: http://cb-nlp-resource-repository-service/v1/resource?type={lexicon-type}&instance={instance-id}&id={account-id}
