[package]
name = "clb"
version = "0.1.0"
authors = ["Ihar Hancharenka <iigoncharenko@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
error-chain = "0.12.0"
docopt = "1.0.2"
serde = "1.0.82"
serde_derive = "1.0.82"
