package mygwt.common.client.url;

import com.google.gwt.core.client.GWT;

public enum Service {
    /*SOURCE_HIGHLIGHTER_SERVICE, REPORT, SETTINGS_SERVICE, ADHOC_SERVICE, PROJECTS_SERVICE, PROJECTS_AJAX_SERVICE, 
     SENTIMENTS, SENTIMENT_UPLOAD_SERVICE, CATEGORIZE, CATEGORIZE_AJAX, CLASSIFICATION_SERVICE, NAVIGATORSERVICE, DMSERVICE, DM_AJAX_SERVICE, ALERTS_SERVICE, MODELSSERVICE
     , SOCIAL_MEDIA_SERVICE, ADHOC_AJAX_SERVICE, PROJECTS_IMPORT_EXPORT_SERVICE, MODEL_MERGE_SERVICE,
     REPORT_AJAX_SERVICE, ACCOUNT_CHECK_AJAX_SERVICE, ADMIN_SERVICE, THEME_DETECTION_SERVICE, ALERTS_WORKFLOW_SERVICE, ALERTS_WORKFLOW_SERVICE_AJAX, CUSTOM_CALENDAR_REMOTE_SERVICE, DERIVED_ATTRIBUTES_REMOTE_SERVICE, TAXONOMY_REMOTE_SERVICE, INSIGHTS_DECK_MODEL_SERVICE, INSIGHTS_DECK_NODE_SERVICE,
     STREAMINGSOURCE_SERVICE, INSIGHTS_DECK_REPORT_SERVICE, INSIGHTS_DECK_MODEL_AJAX_SERVICE, CHARTDATASERVICE, DATALOADER_SERVICE,
     CLASSIFICATION_NODE_INFO_SERVICE, SESSION_VALIDATION_SERVICE, NOTIFICATIONS_SERVICE, NOTIFICATIONS_AJAX_SERVICE, HIERARCHY_SERVICE, SHARED_LEXICON_SERVICE*/
    RECENT_SENTIMENT_EXPORTS_SERVICE
    ;

    
    public String getAbsoluteUrl() {
        return GWT.getHostPageBaseURL() + this.name().toLowerCase();
    }

    @Override
    public String toString() {
        return getAbsoluteUrl();
    }
}
