@echo off
set ES_HOST=wildblue1
set ES_PORT=9200
set PRJ_ID=757399
::1234
::set GEN=1
set DOC_ID=27850674

::set PRJ_INDEX=%PRJ_ID%_%GEN%
set PRJ_INDEX=%PRJ_ID%
set PRJ_READ_ALIAS=read_%PRJ_ID%
set PRJ_WRITE_ALIAS=write_%PRJ_ID%
set ES_HOSTPORT=%ES_HOST%:%ES_PORT%
