[package]
name = "csv-normalize"
version = "0.1.0"
authors = ["Ihar Hancharenka <iigoncharenko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
