---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# verifier:
#   name: inspec

platforms:
  - name: windows-2012r2
    # - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[hello::default]
    # verifier:
    #   inspec_tests:
    #     - test/recipes
    # attributes:
