Vagrant.configure("2") do |config|
  config.vm.box = "hfm4/centos7"
  config.vm.hostname = "myco7"
  config.vm.network "private_network", ip: "192.168.56.2"

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "co7"

    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
end
