---
- hosts: "{{hosts}}"
  become: yes
 
  vars:
    new_user: "prediction"
 
  tasks:
    - name: adduser var trace
      debug: 'msg="hosts: {{hosts}} new_user: {{new_user}}"'

    #- name: remove prediction user if any
    #  user: name="{{new_user}} state=absent remove=yes
    #  become: yes

    - name: add user 
      user: name="{{new_user}}" groups="wheel" state="present"
