---
- hosts: "{{hosts}}"
  become: yes
 
  tasks:
    - name: adduser var trace
      debug: 'msg="hosts: {{hosts}} user: {{user}} new_user: {{new_user}}"'

    #- name: remove new user if any
    #  user: name="{{new_user}}" state=absent remove=yes
    #  become: yes

    - name: add user 
      user: name="{{new_user}}" groups="wheel" state="present"
