---
- hosts: "{{hosts}}"
  become: yes
  become_user: "{{new_user}}"
 
  pre_tasks:
    - name: conda variable trace
      debug: 'msg="hosts: {{hosts}} user: {{user}} new_user: {{new_user}}"'

  #roles:
  #   - robinandeer.miniconda

  vars:
    miniconda_url: >
      http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    miniconda_home: "/home/{{new_user}}/miniconda"
    miniconda_modify_path: true
    miniconda_add_condarc: true
    miniconda_rcfile: "/home/{{new_user}}/.bashrc"
    miniconda_environments:
    - name: "{{new_user}}"
      python_version: 2.7
      pkgs: 'pip'   
      # ipython

  environment: env

  tasks:
    - name: check if already installed
      stat: path={{miniconda_home}}/bin/conda
      register: bin_conda
      changed_when: bin_conda.stat.exists == False

    - name: download miniconda installer
      get_url:
        url={{ miniconda_url }}
        dest=/tmp/miniconda.sh
        mode=0755
      register: miniconda_downloaded
      when: bin_conda.stat.exists == False

    - name: install miniconda
      shell: "/tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash"
      register: miniconda_installed
      when: miniconda_downloaded | success
      notify:
        - remove miniconda setup script
        - update conda to latest version


    - name: install base condarc
      copy: src=files/{{item}} dest="/home/{{new_user}}/.{{item}}"
      with_items:
        - condarc
      when: miniconda_add_condarc

    - name: add miniconda to the PATH
      lineinfile:
        dest: "{{miniconda_rcfile}}"
        line: "export PATH={{miniconda_home}}/bin:$PATH"
        state: present
      when: miniconda_modify_path

    - name: create environments
      shell: "{{ miniconda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} {{ item.pkgs }} creates={{ miniconda_home }}/envs/{{ item.name }}"
      when: miniconda_installed | success
      with_items: miniconda_environments


  handlers:
    - name: remove miniconda setup script
      file: name=/tmp/miniconda.sh state=absent

    - name: update conda to latest version
      shell: "{{ miniconda_home }}/bin/conda update conda --yes -q executable=/bin/bash"
