---
- hosts: "{{hosts}}"
  become: yes
  become_user: "{{new_user}}"

  environment: env

  tasks:
    - name: deps-pip variable trace
      debug: 'msg="hosts: {{hosts}} user: {{user}}"'

    - name: copy pip requirements file
      copy: src=files/{{item}} dest="/home/{{new_user}}/{{item}}"
      with_items:
        - pip-requirements.txt

    - name: copy pip requirements installer file
      copy: src=files/{{item}} dest="/home/{{new_user}}/{{item}}" mode=0755
      with_items:
        - inst_pip.sh

    - name: install pip libs
      shell: "/home/{{new_user}}/inst_pip.sh"
