---
- hosts: "{{hosts}}"
  become: yes
 
  #roles:
    #- ansiblebit.oracle-java

    #- groover.java
    #- williamyeh.oracle-java

  vars:
    #util_epel_enable: false
    #util_action_become_enable: false
    #util_local_action_become_enable: false
    #util_local_action_sudo_enable: false
    ##util_action_become_user: ihar.hancharenka
    ##util_local_action_become_user: iharh

    #java_version: 8
    #java_subversion: 65
    #java_download_path: '/tmp'
    #java_remove_download: true

  tasks:
    - name: jdk var trace
      debug: 'msg="host: {{hosts}}"'

    - name: jdk install
      command: "curl -Lk -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o /home/{{ user  }}/jdk-8u5-linux-x64.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz"

      #get_url: url=http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz dest="home/{{user}}/" headers='Cookie:oraclelicense=accept-securebackup-cookie'
