---
- hosts: "{{hosts}}"
  become: yes
 
  roles:
    - williamyeh.oracle-java

  vars:
    java_version: 8
    java_subversion: 65
    java_download_path: '/tmp'
    #java_download_path: '/home/{{user}}'
    java_remove_download: true

  environment: env

  pre_tasks:
    - name: jdk var trace
      debug: 'msg="host: {{hosts}}"'

    - name: jdk evn trace
      command: 'echo http_proxy: $http_proxy  https_proxy: $https_proxy'
