Vagrant.configure("2") do |config|
  hname = "epbygomw0024t2"

  config.vm.box = "hfm4/centos7"
  config.vm.hostname = "#{hname}"

  config.ssh.insert_key = false
  config.ssh.paranoid = false

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "#{hname}"

    vb.gui = true

    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ['modifyvm', :id, '--vram', '9']
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']

    # UserManual.pdf 8.2.2 Networking settings

    vb.customize ["modifyvm", :id, "--nic1", "nat"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]

    vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
    vb.customize ["modifyvm", :id, "--nictype2", "82543GC"] # T
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapter"]
  end

  config.vm.provision "shell", inline: "hostnamectl set-hostname #{hname}"
  # TODO: deal with copy-paste
  config.vm.provision "shell", inline: "echo '192.168.235.102 epbygomw0024t1 epbygomw0024t1.gomel.epam.com' >> /etc/hosts"

  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = "https://epbygomw0024t1.gomel.epam.com/organizations/cheforg"

    chef.validation_client_name = "cheforg-validator"
    chef.validation_key_path = "cheforg-validator.pem"

    chef.delete_node = true
    chef.delete_client = true
  end
end

# INFO ssh: Attempting SSH connection...
# INFO ssh: Attempting to connect to SSH...
# INFO ssh:   - Host: 127.0.0.1
# INFO ssh:   - Port: 2222
# INFO ssh:   - Username: vagrant
# INFO ssh:   - Password? false
# INFO ssh:   - Key Path: ["C:/Users/Ihar_Hancharenka/.vagrant.d/insecure_private_key"]
