Vagrant.configure("2") do |config|
  hname = "epbygomw0024t2"
  pname = "epbygomw0024t1"
  p_ip = "192.168.235.102"
  dname = "gomel.epam.com"

  config.vm.box = "hfm4/centos7"
  config.vm.hostname = "#{hname}"

  config.ssh.insert_key = false
  config.ssh.paranoid = false

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "#{hname}"

    vb.gui = true

    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ['modifyvm', :id, '--vram', '9']
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']

    # UserManual.pdf 8.2.2 Networking settings

    vb.customize ["modifyvm", :id, "--nic1", "nat"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]

    vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
    vb.customize ["modifyvm", :id, "--nictype2", "82543GC"] # T
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapter"]
  end

  #config.vm.provision "shell", inline: "hostnamectl set-hostname #{hname}"
  config.vm.provision "shell", inline: "echo '#{p_ip} #{pname} #{pname}.#{dname}' >> /etc/hosts"

  config.vm.provision "chef_client" do |chef|
    #chef.chef_server_url = "https://#{pname}.#{dname}/organizations/cheforg"
    chef.chef_server_url = "https://#{p_ip}/organizations/cheforg"

    chef.validation_client_name = "cheforg-validator"
    chef.validation_key_path = "cheforg-validator.pem"

    chef.add_recipe "s1"

    # /tmp/vagrant-chef/client.rb  http_proxy
    # the local chef-server can't be accessed via proxy
    chef.http_proxy = "http://192.168.235.101:3128"
    chef.https_proxy = "https://192.168.235.101:3128"
    chef.no_proxy = "#{p_ip} #{pname} #{pname}.gomel.epam.com"

    chef.delete_node = true
    chef.delete_client = true
  end
end
