Vagrant.configure("2") do |config|
  config.vm.box = "hfm4/centos7"
  config.vm.hostname = "epbygomw0024t2"
  #config.vm.network "private_network", ip: "192.168.56.2"
  config.ssh.insert_key = false

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  #config.vm.box_url = "file:///F:/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"

  #config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "epbygomw0024t2"

    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
end
