[package]
name = "search-client"
version = "0.1.0"
authors = ["Ihar Hancharenka <iigoncharenko@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
error-chain = "0.12.0"
crossbeam-channel = "0.3.3"
