security:
  oauth2:
    localas:
      client:
        clientId: nlpsvc
        clientSecret: $2a$10$/fYPnwdo3/kY/0BeQZBfnupkz8BDAlNsbgTfINVStpUD3n.woevVO
        accessTokenUri: https://localhost:8091/oauth/token
