logging:
  file: logs/app.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%property{PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint}[] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"
  level:
    root: debug

security:
  oauth2:
    clb:
      client:
        access-token-uri: http://localhost:8081/oauth/token
        client-id: nlpsvc
        client-secret: devsecret
        grant-type: client_credentials
        scope:
          #- cx-designer.api[group='customres-nlpsvc-read']
          - cx-designer.api[group='customres-nlpsvc-write']
